DECLARE @DATAFILTRO DATE = '2024-01-01';

SELECT 
	 A.NUMEROORDEM
	,UPPER(A.[STATUS]) AS [STATUS]
	,UPPER(A.TIPOORDEM) AS TIPO_ORDEM
	,A.DATAABERTURA
	,A.DATACONSERTO
	,A.DATAFECHAMENTO
	,UPPER(A.DEFEITORECLAMADO) AS DEFEITO_RECLAMADO
	,UPPER(B.DESCRICAO) AS FINALIDADE
	,UPPER(C.DESCRICAO) AS DEFEITO_CONSTATADO

FROM TBATWEB_OS AS A

LEFT JOIN ATWEB.[atweb_00012].[dbo].[FinalidadesOrdensServicos] AS B
ON A.IDFINALIDADE = B.ID

LEFT JOIN ATWEB.[atweb_00012].[dbo].[DEFEITOSCONSTATADOS] AS C
ON A.IDDEFEITOCONST = C.ID

WHERE 1=1
	AND A.DATAABERTURA >= @DATAFILTRO
	AND A.[STATUS] NOT IN ('Finalizada (Cancelada pelo Fabricante)' , 'Finalizada (Cancelada pelo Posto)' , 'Finalizada (Reprovada Auditoria)',
	'Finalizada (Sem Resolu��o)')

GROUP BY	 A.NUMEROORDEM
			,A.[STATUS]
			,A.TIPOORDEM
			,A.DATAABERTURA
			,A.DATACONSERTO
			,A.DATAFECHAMENTO
			,A.DEFEITORECLAMADO
			,B.DESCRICAO
			,C.DESCRICAO

ORDER BY 1